### ISSUE TITLE
Duplicate entries in course List

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [michael-mosler/Pius-App-for-Android#2]
While filling in the "Meine Kurse" list, every course is shown twice. If you leave the "activity" and go back in, they are only shown ones.

**Comment by Th3Ph4nt0m** [comment]
onResume is executed again after "standby", so the list display must be cleared once before each loading.

I'm on it.

**Comment by Th3Ph4nt0m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Double-Entries in Course-List](https://trello.com/c/GpKzEM8x/19-double-entries-in-course-list)

**Comment by Th3Ph4nt0m** [comment]
Fixed in [this commit](https://github.com/michael-mosler/Pius-App-for-Android/commit/2a7e736b12830a2881c416692c21099007c6b8f5)

**Comment by Th3Ph4nt0m** [comment]
Request for review and merge if necessary @michael-mosler

**Comment by michael-mosler** [comment]
There is no PR in open state. Have you pushed and created a PR in this repo?

**Comment by Th3Ph4nt0m** [comment]
It was just one line so i pushed directly to the develop-branch, hope that was okay. Should i create a PR to the master?

**Comment by michael-mosler** [comment]
Nope, as develop is our main branch we will not have PRs based onto master. For now it's ok. But in future: Even a single liner may break the app. So, actually we should have Ps for any change.

Please move ticket to "Done" state.

**Comment by Th3Ph4nt0m** [comment]
Okay, many thanks! We will create subbranches for the next changes.
