### ISSUE TITLE
[BUG] Active days are grey-colored

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [michael-mosler/Pius-App-for-Android#36]
**Describe the bug**
When Monday and Friday are filled and you click on Monday, the Friday-Button changes to a grey color, but remains active.

**To Reproduce**
1. Go to Vertretungsplan
2. Click on Monday
3. Click on Friday (grey)

**Expected behavior**
Friday should not be impacted by clicking the Monday.

**Screenshots**
![Screenshot_20210303-083236.jpg](https://user-images.githubusercontent.com/44142235/109770094-69627500-7bfb-11eb-83b8-e0777f6031fd.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: Android 11 / Oxygen OS 11 Beta 3
 - Version: 1.6.0

**Additional context**
The Friday turns back blue on `onReload`.

**Comment by michael-mosler** [comment]
Situation is somewhat different. If there is a sequence of active/inactive/active and you unfold and fold the first item then the last one gets inactive but can be unfolded.

Actually it must not get inactive.

Hm, cannot reproduce twice; something else must happen in between.

**Comment by michael-mosler** [comment]
It is sufficient to unfold a longer item when there is an inactive one. When then view is scrolled all items that scroll in are greyed. What the hell! This seems to be a new bug, may be under newer Android versions.

**Comment by Th3Ph4nt0m** [comment]
Possible, can't reproduce on Android 8.1.0
