### ISSUE TITLE
Update minimum SDK level

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [michael-mosler/Pius-App-for-Android#48]
Our current minimum SDK level is 19. By updating it to 27, we are able to take the following changes:

- App-Lock (Fingerprint)
- Improving Autofill-Support
- Text-Selection (Copy EVA-notices to clipboard)
- App Shortcuts (Long-Press the app for e.g. going directly to the dashboard)
- Prioritized Notifications
- Auto-sizing Text-Views
- Optimizing WebView

**Comment by michael-mosler** [comment]
Raised level to 25. With 27 we currently would loose a whole bunch of users.
