### ISSUE TITLE
[BUG] Red navbar not updating

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [michael-mosler/Pius-App-for-Android#49]
**Describe the bug**
As far as I know, the red icons in the navbar indicate that the offline plan is displayed. When you get an internet connection again, the color is not updated.

**To Reproduce**
1. Turn off your Internet connection(s)
2. Go to "Vertretungsplan"
3. See red color (correct)
4. Reconnect to the internet
5. Reload the "Vertretungsplan"
6. See that the color stays red (Not correct)

**Expected behavior**
The Navbar should turn back to the default color (blue) when the "Vertretungsplan" is updated (from remote).

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: Android 11 (OxygenOS)
 - Version 1.7.0

**Comment by Th3Ph4nt0m** [comment]
Bug ist reproducible in App Version 1.6.0 and Android 8.1 as well.

**Comment by michael-mosler** [comment]
Cannot reproduce in simulator. When disconnecting icons are colored red getting blue after reconnecting.
