### ISSUE TITLE
Redesign of the App

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [michael-mosler/Pius-App-for-Android#9]
**Describe the solution you'd like**
The "What's New" content displayed as a pop-up dialogue.
-> More beautiful design, will be seen better

**Additional context**
White background, banner in "PiusBlue". One icon per new feature.

**Comment by michael-mosler** [comment]
Unable to build branch. Build fails with undefined class IOBackButtonPress and missing file in .idea.
